JS_Labs_Dev
ScumEater/JS_Labs pull request #2
Opened 2021-11-25 18:42 UTC by ScumEater

2021-11-25 19:20 UTC, ScumEater commented
1. Переработан метод draw в файле rectangle.js;
2. Убрана лишняя информация из index,html;
3. Отформатирован код в index.html;
4. Добавлена возможность  выбора количества генерируемых строк и столбцов в rectangle.js

2021-11-25 19:36 UTC, volodink requested changes
1. Необходимо понять, что откуда вызывается и что именно чем занимается.
2. Один класс - одна цель.
3. Методы должны делать то, то как они описаны.

2021-11-25 19:36 UTC, volodink commented on index.html
> +<title>Зе бест калькулятор</title>
Не уверен, что заголовок такой в этом задании.

2021-11-25 19:36 UTC, volodink commented on js/app.js
> +        let rectangle = new Rectangle();
1. Если все переносится все в отдельный класс, то его надо переименовать в ```Rectangles```, например.
2. Это не решает проблему, и у класса ```Rectangles``` будет зависимый класс ```Rectangle```.

2021-11-25 19:36 UTC, volodink commented on js/app.js
> +app.generateRectangles();
1. Метод выглядит как внутренний.
2. Возможно, стоит показывать наружу что-то типа ```run```.

2021-11-25 19:36 UTC, volodink commented on js/rectangle.js
> +        this.ctx = canvas.getContext('2d');
Возможно, было бы хорошей идеей получать контекст из ```Application```.

2021-11-25 19:36 UTC, volodink commented on css/index.css
> +body {
Все эти стили все еще нужны или что-то можно выпилить?

2021-11-25 19:36 UTC, volodink commented on js/rectangle.js
> +    randomColor() {
Выглядит как кандидат на выделение в отдельный класс.

2021-11-30 20:00 UTC, ScumEater commented on css/index.css
> +body {
Убрал ненужные стили

2021-11-30 20:01 UTC, ScumEater commented on js/rectangle.js
> +    randomColor() {
RandomColor теперь отдельный метод, выполняющий функцию генерации цвета

2021-11-30 20:01 UTC, ScumEater commented on js/app.js
> +app.generateRectangles();
Переименовал методы в более уместные

2021-11-30 20:01 UTC, ScumEater commented on index.html
> +<title>Зе бест калькулятор</title>
Заголовок исправлен

2021-12-02 09:45 UTC, merged